baseURL = 'https://iskyd.github.io'
languageCode = 'en-us'
title = 'Hello'
theme = "archie"

pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

paginate=4

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/iskyd"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/iskypitts/"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[params]
mode="toggle" # color-mode → light,dark,toggle or auto